AWSTemplateFormatVersion: 2010-09-09
Description: Client Security Group
Metadata: 
  AWS::CloudFromation::Interface:
    ParameterGroups:
    - Label:
        default: Parent Stacks
      Parameters:
      - ParentVPCStack
Parameters: 
  ParentVPCStack:
    Description: Stack name of parent VPC stack based on vpc-1az.yaml template.
    Type: String

Resources: 
  ClientSecurityGroup: 
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref AWS::StackName
      VpcId:  {'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'}

Outputs:
  StackName:
    Description: Stack name.
    Value: !Sub ${AWS::StackName}
  
  ClientSecurityGroup:
    Description: Use this Security Group to reference client traffic.
    Value: !Ref ClientSecurityGroup
    Export:
      Name: !Sub ${AWS::StackName}-ClientSecurityGroup