service: aws-node-scheduled-cron

useDotenv: true

custom:
  queueName: ModerationQueue

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource:
        Fn::GetAtt: [SQSQueue, Arn]
    - Effect: "Allow"
      Action:
        - "states:ListStateMachines"
      Resource:
        - 'arn:aws:states:us-east-1:215348766906:stateMachine:*'
    - Effect: "Allow"
      Action:
        - "states:StartExecution"
      Resource:
        - "arn:aws:states:us-east-1:215348766906:stateMachine:ModerationEngine*"

functions:
  start-lambda:
    handler: handler.start
    # events:
      # Invoke Lambda function every minute
      # - schedule: rate(1 minute)
    environment:
      REGION: "us-east-1"
      HOSTNAME: "localhost"
      PORT: 8080 
      PATH: "api/items/inreview"
      TARGET_BUCKET: "octank-moderation"
      SQS_URL:
        Ref: SQSQueue
  end-lambda:
    handler: handler.end
    environment:
      STATE_MACHINE_NAME: "ModerationEngine"
    events:
      - sqs:
          arn:
            Fn::GetAtt: [SQSQueue, Arn]

resources:
  Resources:
    SQSQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:custom.queueName}

plugins:
  - serverless-dotenv-plugin